//s_add new sensor driver here
//export funtions

//----------wtk imgsensor list start----------
/*IMX*/
UINT32 IMX219_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 IMX2190_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 IMX149_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
/*OV*/
UINT32 OV5648_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 OV8858_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 OV56480_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 OV8865_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 OV5693_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 OV9762_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 OV8856_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 OV5670_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
/*S5K*/
UINT32 S5K5E2YA_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 S5K3M2_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 S5K3L8_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 S5K3H7YX_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 S5K4H8_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 S5K4H5YC_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
/*HI*/
UINT32 HI551_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 HI553_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 HI545_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 HI843B_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
/*MT*/

/*GC*/
UINT32 GC0409_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 GC2355_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 GC030AMIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 GC5024_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 GC8024_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 GC2365_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 GC5005MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
/*C*/
UINT32 C2590_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
/*SP*/
UINT32 SP2508_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 SP5409_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 SP2509_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 SP0A09_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
UINT32 SP5506_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);
/*A*/

/*HM*/

/*AR*/

/*SIV*/

/*PAS (PixArt Image)*/

/*Panasoic*/
UINT32 MN34152_MIPI_RAW_SensorInit(PSENSOR_FUNCTION_STRUCT *pfFunc);

/*Toshiba*/

/*Others*/

//----------wtk imgsensor list end  ----------


//! Add Sensor Init function here
//! Note:
//! 1. Add by the resolution from ""large to small"", due to large sensor
//!    will be possible to be main sensor.
//!    This can avoid I2C error during searching sensor.
//! 2. This file should be the same as mediatek\custom\common\hal\imgsensor\src\sensorlist.cpp
ACDK_KD_SENSOR_INIT_FUNCTION_STRUCT kdSensorList[MAX_NUM_OF_SUPPORT_SENSOR+1] =
{
//----------wtk imgsensor list start----------
/*IMX*/
#if defined(IMX219_MIPI_RAW)
    {IMX219_SENSOR_ID, SENSOR_DRVNAME_IMX219_MIPI_RAW, IMX219_MIPI_RAW_SensorInit},
#endif
#if defined(IMX2190_MIPI_RAW)
    {IMX2190_SENSOR_ID, SENSOR_DRVNAME_IMX2190_MIPI_RAW, IMX2190_MIPI_RAW_SensorInit},
#endif
#if defined(IMX149_MIPI_RAW)
    {IMX149_SENSOR_ID, SENSOR_DRVNAME_IMX149_MIPI_RAW, IMX149_MIPI_RAW_SensorInit},
#endif
/*OV*/
#if defined(OV5648_MIPI_RAW)
    {OV5648_SENSOR_ID, SENSOR_DRVNAME_OV5648_MIPI_RAW, OV5648_MIPI_RAW_SensorInit},
#endif
#if defined(OV8858_MIPI_RAW)
    {OV8858_SENSOR_ID, SENSOR_DRVNAME_OV8858_MIPI_RAW, OV8858_MIPI_RAW_SensorInit},
#endif
#if defined(OV56480_MIPI_RAW)
    {OV56480_SENSOR_ID, SENSOR_DRVNAME_OV56480_MIPI_RAW, OV56480_MIPI_RAW_SensorInit},
#endif
#if defined(OV8865_MIPI_RAW)
    {OV8865_SENSOR_ID, SENSOR_DRVNAME_OV8865_MIPI_RAW, OV8865_MIPI_RAW_SensorInit},
#endif
#if defined(OV5693_MIPI_RAW)
    {OV5693_SENSOR_ID, SENSOR_DRVNAME_OV5693_MIPI_RAW, OV5693_MIPI_RAW_SensorInit},
#endif
#if defined(OV9762_MIPI_RAW)
    {OV9762_SENSOR_ID, SENSOR_DRVNAME_OV9762_MIPI_RAW, OV9762_MIPI_RAW_SensorInit},
#endif
#if defined(OV8856_MIPI_RAW)
    {OV8856_SENSOR_ID, SENSOR_DRVNAME_OV8856_MIPI_RAW, OV8856_MIPI_RAW_SensorInit},
#endif
#if defined(OV5670_MIPI_RAW)
    {OV5670MIPI_SENSOR_ID, SENSOR_DRVNAME_OV5670_MIPI_RAW, OV5670_MIPI_RAW_SensorInit},
#endif
/*S5K*/
#if defined(S5K5E2YA_MIPI_RAW)
    {S5K5E2YA_SENSOR_ID, SENSOR_DRVNAME_S5K5E2YA_MIPI_RAW, S5K5E2YA_MIPI_RAW_SensorInit},
#endif
#if defined(S5K3M2_MIPI_RAW)
    {S5K3M2_SENSOR_ID, SENSOR_DRVNAME_S5K3M2_MIPI_RAW, S5K3M2_MIPI_RAW_SensorInit},
#endif
#if defined(S5K3L8_MIPI_RAW)
    {S5K3L8_SENSOR_ID, SENSOR_DRVNAME_S5K3L8_MIPI_RAW, S5K3L8_MIPI_RAW_SensorInit},
#endif
#if defined(S5K3H7YX_MIPI_RAW)
    {S5K3H7YX_SENSOR_ID, SENSOR_DRVNAME_S5K3H7YX_MIPI_RAW, S5K3H7YX_MIPI_RAW_SensorInit},
#endif
#if defined(S5K4H8_MIPI_RAW)
    {S5K4H8_SENSOR_ID, SENSOR_DRVNAME_S5K4H8_MIPI_RAW, S5K4H8_MIPI_RAW_SensorInit},
#endif
#if defined(S5K4H5YC_MIPI_RAW)
    {S5K4H5YC_SENSOR_ID, SENSOR_DRVNAME_S5K4H5YC_MIPI_RAW, S5K4H5YC_MIPI_RAW_SensorInit},
#endif
/*HI*/
#if defined(HI551_MIPI_RAW)
    {HI551_SENSOR_ID, SENSOR_DRVNAME_HI551_MIPI_RAW,HI551_MIPI_RAW_SensorInit},
#endif

#if defined(HI553_MIPI_RAW)
    {HI553_SENSOR_ID, SENSOR_DRVNAME_HI553_MIPI_RAW,HI553_MIPI_RAW_SensorInit},
#endif
#if defined(HI545_MIPI_RAW)
    {HI545_SENSOR_ID, SENSOR_DRVNAME_HI545_MIPI_RAW,HI545_MIPI_RAW_SensorInit},
#endif
#if defined(HI843B_MIPI_RAW)    
	{HI843B_SENSOR_ID, SENSOR_DRVNAME_HI843B_MIPI_RAW,HI843B_MIPI_RAW_SensorInit},
#endif
/*MT*/

/*GC*/
#if defined(GC0409_MIPI_RAW)
    {GC0409_SENSOR_ID, SENSOR_DRVNAME_GC0409_MIPI_RAW, GC0409_MIPI_RAW_SensorInit},
#endif
#if defined(GC2355_MIPI_RAW)
    {GC2355_SENSOR_ID, SENSOR_DRVNAME_GC2355_MIPI_RAW, GC2355_MIPI_RAW_SensorInit},
#endif
#if defined(GC030AMIPI_RAW)
    {GC030AMIPI_SENSOR_ID, SENSOR_DRVNAME_GC030AMIPI_RAW,GC030AMIPI_RAW_SensorInit},
#endif
#if defined(GC5024_MIPI_RAW)
    {GC5024_SENSOR_ID, SENSOR_DRVNAME_GC5024_MIPI_RAW,GC5024_MIPI_RAW_SensorInit},
#endif
#if defined(GC8024_MIPI_RAW)
    {GC8024_SENSOR_ID, SENSOR_DRVNAME_GC8024_MIPI_RAW,GC8024_MIPI_RAW_SensorInit},
#endif
#if defined(GC2365_MIPI_RAW)
    {GC2365_SENSOR_ID, SENSOR_DRVNAME_GC2365_MIPI_RAW, GC2365_MIPI_RAW_SensorInit},
#endif
#if defined(GC5005_MIPI_RAW)
	{GC5005MIPI_SENSOR_ID, SENSOR_DRVNAME_GC5005_MIPI_RAW,GC5005MIPI_RAW_SensorInit},
#endif
/*C*/
#if defined(C2590_MIPI_RAW)
	{C2590_SENSOR_ID, SENSOR_DRVNAME_C2590_MIPI_RAW, C2590_MIPI_RAW_SensorInit},
#endif
/*SP*/
#if defined(SP2508_MIPI_RAW)
    {SP2508_SENSOR_ID, SENSOR_DRVNAME_SP2508_MIPI_RAW, SP2508_MIPI_RAW_SensorInit},
#endif

#if defined(SP5409_MIPI_RAW)
    {SP5409_SENSOR_ID, SENSOR_DRVNAME_SP5409_MIPI_RAW, SP5409_MIPI_RAW_SensorInit},
#endif
#if defined(SP2509_MIPI_RAW)
    {SP2509_SENSOR_ID, SENSOR_DRVNAME_SP2509_MIPI_RAW, SP2509_MIPI_RAW_SensorInit},
#endif
#if defined(SP0A09_MIPI_RAW)
    {SP0A09_SENSOR_ID, SENSOR_DRVNAME_SP0A09_MIPI_RAW, SP0A09_MIPI_RAW_SensorInit},
#endif
#if defined(SP5506_MIPI_RAW)
    {SP5506_SENSOR_ID, SENSOR_DRVNAME_SP5506_MIPI_RAW, SP5506_MIPI_RAW_SensorInit},
#endif
/*A*/

/*HM*/

/*AR*/

/*SIV*/

/*PAS (PixArt Image)*/

/*Panasoic*/
#if defined(MN34152_MIPI_RAW)    
	{MN34152_SENSOR_ID, SENSOR_DRVNAME_MN34152_MIPI_RAW, MN34152_MIPI_RAW_SensorInit},
#endif
/*Toshiba*/

/*Others*/

//----------wtk imgsensor list end  ----------

/*  ADD sensor driver before this line */
    {0,{0},NULL}, //end of list
};
//e_add new sensor driver here

