language: c
#######################################################################################
os:
  - linux
  
addons:
  apt:
    packages:
      - curl

#######################################################################################


before_install:
  - sudo apt-get update -qq
#######################################################################################


script:  
  - export BUILDING_ON_CI=y
  - travis_wait 15 ./build -b

after_success:
  - curl --upload-file *snowy*.zip https://transfer.sh
