language: c
#######################################################################################
os:
  - linux
  
addons:
  apt:
    packages:
      - curl

#######################################################################################


before_install:
  - sudo apt-get update -qq
#######################################################################################


script:  
  - export BUILDING_ON_CI=y
  - travis_wait 20 ./build -b
