ccflags-y += -I$(srctree)/drivers/misc/mediatek/mach/$(MTK_PLATFORM)/$(subst ",,$(CONFIG_ARCH_MTK_PROJECT))/alsps/epl259x/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/alsps/epl259x/inc/

ccflags-y += -I$(srctree)/drivers/misc/mediatek/alsps/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include

obj-y	:=  epl259x.o

