$(info $(srctree)/drivers/misc/mediatek/mach/$(MTK_PLATFORM)/$(subst ",,$(CONFIG_ARCH_MTK_PROJECT))/leds/aw2013)

ccflags-y += -I$(srctree)/drivers/misc/mediatek/mach/$(MTK_PLATFORM)/$(subst ",,$(CONFIG_ARCH_MTK_PROJECT))/leds/aw2013/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/leds/mt6735/aw2013/inc/

obj-y	:=  aw2013.o
