#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += JD9161_HONGZHAN_TN_HFW50194QRA_IVO_DSI_2_VDO_FWVGA.o



ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
