subdir-ccflags-y += -Werror
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek
# In case the platform does NOT support this type of sensors
obj-y   +=  mtk_tpd.o
obj-y   +=  tpd_button.o
obj-y   +=  tpd_calibrate.o
obj-y   +=  tpd_debug.o
obj-y   +=  tpd_default.o
obj-y   +=  tpd_init.o
obj-y   +=  tpd_misc.o
obj-y   +=  tpd_setting.o


obj-$(CONFIG_TOUCHSCREEN_MTK_GT1151)	+=  GT1151/
obj-$(CONFIG_TOUCHSCREEN_MTK_GT910)	+=  GT910/
obj-$(CONFIG_TOUCHSCREEN_MTK_GT9XXTB_HOTKNOT)	+=  GT9XXTB_hotknot/
obj-$(CONFIG_TOUCHSCREEN_MTK_SYNAPTICS_I2C_RMI4)	+=  synaptics_i2c_rmi4/
obj-$(CONFIG_TOUCHSCREEN_MTK_GT928)	+=  GT928/
obj-$(CONFIG_TOUCHSCREEN_MTK_GT9XX_HOTKNOT_SCP)	+=  GT9XX_hotknot_scp/
obj-$(CONFIG_TOUCHSCREEN_MTK_GT911)	+=  GT911/
obj-$(CONFIG_TOUCHSCREEN_MTK_FT5X0X)	+=  ft5x0x/
obj-$(CONFIG_WTK_MSG2238_X2605)	+=  msg2238_x2605/
obj-$(CONFIG_WTK_MSG2238_X2605_s4)	+=  msg2238_x2605_s4/
obj-$(CONFIG_WTK_MSG2238_X5623)	+=  msg2238_x5623/
obj-$(CONFIG_WTK_MSG2238_X5057)	+=  msg2238_x5057/
obj-$(CONFIG_WTK_FT6336_S3619)	+=  ft6336_s3619/
obj-$(CONFIG_WTK_GT9XX_HOTKNOT_X5613)	+=gt9xx_hotknot_x5613/
obj-$(CONFIG_WTK_GT9XX_HOTKNOT_X5618)	+=gt9xx_hotknot_x5618/
obj-$(CONFIG_WTK_GT9XX_HOTKNOT_M6010)	+=gt9xx_hotknot_m6010/
obj-$(CONFIG_WTK_GT9XX_HOTKNOT_X5602)	+=gt9xx_hotknot_x5602/
obj-$(CONFIG_WTK_FT6336_X2605)	+=  ft6336_x2605/
obj-$(CONFIG_WTK_GT5668_X5623)	+=  GT5668/
obj-$(CONFIG_WTK_GT5668_X6068)	+=  GT5668_X6068/
obj-$(CONFIG_WTK_GT5668_X6069)	+=  GT5668_X6069/
obj-$(CONFIG_WTK_GT9XX_HOTKNOT_X5057)	+=gt9xx_hotknot_x5057/
obj-$(CONFIG_WTK_GT9XX_HOTKNOT_X6069)	+=gt9xx_hotknot_x6069/
obj-$(CONFIG_WTK_GSL1691_X5623)	+=gsl1691_x5623/
